### ISSUE TITLE
January 22, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by sz16900** [Flakster/Newsweek-clone#2]
The page is looking awesome Carlos, here is a little suggestion:

- Try using more semantic HTML when writing your code. It'll make it more readable and awesome!

**Comment by jabichris** [comment]
Nice work @Flakster. Small things to take into consideration before submitting for review:

- Make sure you fix this validation errors
<img width="1381" alt="Screen Shot 2020-01-22 at 16 13 27" src="https://user-images.githubusercontent.com/33568373/72901459-7e02e700-3d32-11ea-9063-6577fb181b57.png">

- Then you need to consider the convention when writing your commit message.

**Comment by Flakster** [comment]
Done. Thanks for your feedback
